### PR TITLE
#164: Extract author & committer usernames from emails if fetching usernames from API fails.

### LINKED ISSUE #164: Fetch contributors from commit co-authors

### PR DESCRIPTION
**Pull request by joeparsons**
Closes #164 (?)

I'm guessing the reason author and committer usernames don't seem to be able to be fetched from the GitLab API is that the users API endpoint is not public and requires authentication of some kind (https://docs.gitlab.com/ee/api/rest/#authentication).

I was confused about this at first because I found I was able to load the users endpoint in my browser but later realized that my git.drupalcode.org web session cookie was making this work (https://docs.gitlab.com/ee/api/rest/#session-cookie).

This PR adds fallback code that will try to use a regex to extract the usernames from the commit author and committer email fields when the users API endpoint is inaccessible.

### CODE REVIEW

File: api/src/Changelog.php [hunk 1]
```diff
@@ -38,18 +38,27 @@ public function __construct(
         $contributors = [];
         foreach ($commits as $commit) {
             $commitContributors = CommitParser::extractUsernames($commit->title);
+            $emailUsernameRegex = '/(?<=[0-9]-)([a-zA-Z0-9-_\.]{2,255})(?=@users\.noreply\.drupalcode\.org)/';
```
Comment (mglaman) [inline api/src/Changelog.php:41]: We can define this above the loop since it doesn't change

**Review by mglaman — COMMENTED** [review]
Ugh I even knew about the GitLab API users problem with being authenticated via cookie. I still committed this. Thanks for this improvement. Tests may need to be updated to verify

File: api/src/Changelog.php (hunk 1 above)
Comment (joeparsons) [reply api/src/Changelog.php]: Good call.  Fixed.

**Comment by mglaman** [comment]
Thanks!!
